//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edms.Kore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string FileHash { get; set; }
        public string Folder { get; set; }
        public string FileName { get; set; }
        public string Content { get; set; }
        public Nullable<int> FileSizeKB { get; set; }
        public Nullable<int> FileSection { get; set; }
    }
}
